---
- name: General Housekeeping
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ autodeploy_path }}/webhook-listener.js"
    - "{{ autodeploy_path }}/webhooks/deploy"
    - "{{ autodeploy_path }}/webhook-listener"
    - /data/run/webhooks
    - /etc/monit/conf.d/webhook-listener
    - /etc/nginx/sites-available/webhooks.conf
    - /etc/nginx/sites-enabled/webhooks
  tags:
    - autodeploy
