---
- name: Directories Exists | Deployment
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ autodeploy_user }}"
    group: wcadmin
    mode: 0750
  tags:
    - directory-structure
    - security-concern
    - deployment
  with_items:
    - /var/www/.ssh
    - /data/deployment

- name: Setup Automated Deployment | Playbook
  template:
    src: data/deployment/deploy.yml
    dest: /data/deployment/deploy.yml
    owner: root
    group: wcadmin
    mode: 0444
  when: autodeploy_using_standard_playbook
  tags:
    - deployment
    - using-ansible

- name: Configure | sudo | allow autodeploy to restart application
  lineinfile:
    state: present
    dest: /etc/sudoers
    regexp: "^{{ autodeploy_user }}"
    line: "{{ autodeploy_user }} ALL = NOPASSWD : /usr/bin/monit restart {{ autodeploy_restart_target }}"
    validate: 'visudo -cf %s'
  when: autodeploy_restart_enabled
  tags:
    - sudo
