---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items: package_variants[autodeploy_database_engine]
  when: autodeploy_database_bundled
  tags:
    - software-installation
    - using-apt
    - autodeploy

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - unzip
  when: autodeploy_database_compressed
  tags:
    - software-installation
    - using-apt
    - autodeploy

- name: Install Packages | npm
  npm:
    state: latest
    name: "{{ item }}"
    global: yes
  with_items:
    - forever
  when: autodeploy_listener == 'node'
  tags:
    - autodeploy

- name: Install Packages | bundler
  gem:
    state: latest
    name: bundler
  when: autodeploy_for_ruby
  tags:
    - autodeploy