---
- include: proxy-with-nginx.yml

- name: Setup Automated Deployment | Listener
  template:
    src: data/deployment/listener/index.php
    dest: "{{ autodeploy_listener_docroot }}/index.php"
    owner: "{{ autodeploy_user }}"
    group: www-data
    mode: 0444
  when: autodeploy_using_standard_playbook
  tags:
    - security-concern
    - deployment
