---
- include: proxy-with-haproxy.yml
  when: autodeploy_proxy_method == 'haproxy'
- include: proxy-with-nginx.yml
  when: autodeploy_proxy_method == 'nginx'

- name: "Directory Exists | {{ autodeploy_runtime_root }}"
  file:
    state: directory
    path: "{{ autodeploy_runtime_root }}"
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0775
  tags:
    - directory-structure
    - runtime-data
    - autodeploy

- name: Setup Automated Deployment | Listener
  template:
    src: "data/deployment/listener.js"
    dest: "{{ autodeploy_path }}/listener.js"
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0460
  when: autodeploy_listener == 'node'
  tags:
    - security-concern
    - deployment
    - autodeploy

- name: Setup Automated Deployment | package.json
  template:
    src: "data/deployment/package.json"
    dest: "{{ autodeploy_path }}/package.json"
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0460
  when: autodeploy_listener == 'node'
  tags:
    - security-concern
    - deployment
    - autodeploy

- name: Update Dependencies | npm
  npm:
    state: latest
    path: "{{ autodeploy_path }}"
  tags:
    - autodeploy

- name: Trigger All Callbacks
  meta: flush_handlers
