---
- include: proxy-with-haproxy.yml
  when: autodeploy_proxy_method == 'haproxy'
- include: proxy-with-nginx.yml
  when: autodeploy_proxy_method == 'nginx'

- name: "Directory Exists | {{ autodeploy_runtime_root }}"
  file:
    state: directory
    path: "{{ autodeploy_runtime_root }}"
    owner: "{{ autodeploy_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - runtime-data

- name: Setup Automated Deployment | Listener
  template:
    src: "data/deployment/listener.js"
    dest: "/data/deployment/listener.js"
    owner: www-data
    group: wcadmin
    mode: 0460
  when: autodeploy_listener == 'node'
  tags:
    - security-concern
    - deployment

- name: Setup Automated Deployment | package.json
  template:
    src: "data/deployment/package.json"
    dest: "/data/deployment/package.json"
    owner: www-data
    group: wcadmin
    mode: 0460
  when: autodeploy_listener == 'node'
  tags:
    - security-concern
    - deployment

- name: Update Dependencies | npm
  npm:
    state: latest
    path: /data/deployment

- name: Upload Config | monit | autodeploy
  template:
    src: etc/monit/conf.d/autodeploy
    dest: /etc/monit/conf.d/autodeploy
  notify: Reload Service | monit
  tags:
    - using-monit

- name: Trigger All Callbacks
  meta: flush_handlers
