---
- include: cleanup.yml
- include: install.yml
- include: configure.yml
- include: listen-with-php.yml
  when: autodeploy_listener == 'php'
- include: listen-with-node.yml
  when: autodeploy_listener == 'node'
- include: listen-with-sweatshop.yml
  when: autodeploy_listener == 'sweatshop'

- name: Invoke autodeploy
  command: curl --data "" localhost:81
  when: autodeploy_inital_deploy
