---
- name: Directories Exists | nginx
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0664
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available
  tags:
    - directory-structure
    - security-concern
    - deployment
    - autodeploy

- name: Upload Config | nginx | Automated Deployment
  template:
    src: etc/nginx/sites-available/deployment.conf
    dest: "/etc/nginx/sites-available/{{ autodeploy_name }}.conf"
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0664
  notify: Reload Service | nginx
  tags:
    - configuration
    - template-configuration
    - nginx
    - autodeploy

- name: Enable Config | nginx | Automated Deployment
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ autodeploy_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ autodeploy_name }}"
  notify: Reload Service | nginx
  tags:
    - configuration
    - enable-configuration
    - nginx
    - autodeploy
