---
- name: Directories Exists | /etc/nginx/sites-available
  file:
    state: directory
    path: /etc/nginx/sites-available
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0664
  tags:
    - directory-structure
    - security-concern
    - deployment
    - autodeploy

- name: Upload Config | nginx | Automated Deployment
  template:
    src: etc/nginx/sites-available/deployment.conf
    dest: /etc/nginx/sites-available/deployment.conf
    owner: "{{ autodeploy_user }}"
    group: "{{ autodeploy_group }}"
    mode: 0664
  notify: Reload Service | nginx
  tags:
    - configuration
    - template-configuration
    - nginx
    - autodeploy

- name: Enable Config | nginx | Automated Deployment
  file:
    state: link
    src: /etc/nginx/sites-available/deployment.conf
    dest: /etc/nginx/sites-enabled/deployment
  notify: Reload Service | nginx
  tags:
    - configuration
    - enable-configuration
    - nginx
    - autodeploy
