---
- name: Invoke autodeploy
  command: "curl --request POST localhost:{{ autodeploy_listener_port }}"
  when: autodeploy_initial_deployment | bool
  register: out
  notify: Invoke autodeploy | output

- name: Invoke autodeploy | output
  debug:
    var: out.stdout_lines
